workspace:
  base: /go
  path: src/github.com/appleboy/drone-jenkins

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:

  jenkins:
    image: jenkins/jenkins:lts
    detach: true
    environment:
      JENKINS_HOME: /go/src/github.com/appleboy/drone-jenkins/jenkins_service/jenkins_data/
    commands:
      - id
      - id -u
      - id -g
      - ls -lisa
      
  lint:
    image: golang:1.11
    pull: true
    group: test
    commands:
      - make vet
      - make lint
      - make test-vendor
      - make misspell-check

  test:
    image: golang:1.11
    pull: true
    group: test
    commands:
      - make test
      - make coverage

  build_linux_amd64_with_module:
    image: golang:1.11
    pull: true
    group: build
    environment:
      GO111MODULE: "on"
    commands:
      - make build_linux_amd64

  build_linux_amd64:
    image: golang:1.11
    pull: true
    group: build
    commands:
      - make build_linux_amd64

  build_linux_i386:
    image: golang:1.11
    pull: true
    group: build
    commands:
      - make build_linux_i386

  build_linux_arm64:
    image: golang:1.11
    pull: true
    group: build
    commands:
      - make build_linux_arm64

  build_linux_arm:
    image: golang:1.11
    pull: true
    group: build
    commands:
      - make build_linux_arm

  codecov:
    image: robertstettner/drone-codecov
    secrets: [ codecov_token ]
    when:
      event: [ push, pull_request ]
      status: [ success ]

  release:
    image: golang:1.11
    pull: true
    commands:
      - make release
    when:
      event: [ tag ]
      local: false

  release_tag:
    image: plugins/github-release
    secrets: [ github_release_api_key ]
    group: release
    files:
      - dist/release/*
    when:
      event: [ tag ]
      local: false

  publish_linux_amd64:
    image: plugins/docker:17.12
    group: release
    pull: true
    repo: ${DRONE_REPO}
    secrets: [ docker_username, docker_password ]
    auto_tag: true
    auto_tag_suffix: linux-amd64
    when:
      event: [ push, tag ]
      local: false

  publish_alpine:
    image: plugins/docker:17.12
    group: release
    pull: true
    dockerfile: Dockerfile.alpine
    secrets: [ docker_username, docker_password ]
    auto_tag: true
    auto_tag_suffix: linux-alpine
    repo: ${DRONE_REPO}
    when:
      event: [ push, tag ]
      local: false

  publish_linux_i386:
    image: plugins/docker:17.12
    pull: true
    secrets: [ docker_username, docker_password ]
    group: release
    repo: ${DRONE_REPO}
    auto_tag: true
    auto_tag_suffix: linux-i386
    dockerfile: Dockerfile.i386
    when:
      event: [ push, tag ]
      local: false

  publish_linux_arm64:
    image: plugins/docker:17.12
    pull: true
    secrets: [ docker_username, docker_password ]
    group: release
    repo: ${DRONE_REPO}
    auto_tag: true
    auto_tag_suffix: linux-arm64
    dockerfile: Dockerfile.arm64
    when:
      event: [ push, tag ]
      local: false

  publish_linux_arm:
    image: plugins/docker:17.12
    pull: true
    secrets: [ docker_username, docker_password ]
    group: release
    repo: ${DRONE_REPO}
    auto_tag: true
    auto_tag_suffix: linux-arm
    dockerfile: Dockerfile.arm
    when:
      event: [ push, tag ]
      local: false