# appveyor.yml
version: 1.0.0.{build}

platform: x64

clone_folder: c:\gopath\src\github.com\account\myproject

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env

build_script:
  - make vet
  - make lint
  - make misspell-check